name: Manually Deploy to heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 5d881327-1f1a-4bd2-9904-8982e01da9b1
          heroku_app_name: jdlazyleech
          heroku_email: iamthefoxspirits@protonmail.com
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "us"
        env:
          HD_API_ID: 1957706
          HD_API_HASH: b1fc05cb6e99b67c6fca96538c6d7e7e
          HD_BOT_TOKEN: 2033257854:AAEN0ynXbXvt7e0erE1wSM37s4_CuSAU8bY
          HD_ADMIN_CHATS: 831054990
          HD_NYAA_RSS_LINKS: https://yts.mx/rss/0/720p/all/0/all
          HD_RSS_RECHECK_INTERVAL: 5
          HD_DATABASE_URL: mongodb+srv://jdlazyleech:jdlazyleech@cluster0.85v1y.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
